### ISSUE TITLE
Invisible buttons

### ISSUE THREAD

**Issue by Gminator22** [vinceliuice/matcha#5]
Hi,

When using the matcha controls, some buttons just disappear from menus. I'm not sure if my system lacks some packages or if it's an actual issue.. Here's an example.

![buttons](https://user-images.githubusercontent.com/32374226/30990349-e905cf9a-a46e-11e7-8005-bbbad1505790.png)
![nobutton](https://user-images.githubusercontent.com/32374226/30990350-e906e498-a46e-11e7-9d59-8b8683dc7fc1.png)

Am I the only one who had this problem so far?
Thank you!

**Comment by vinceliuice** [comment]
Sorry! Matcha only support gtk3.20 or later, if you are using linuxmint, then you should update you gnome-base version (because linuxmint18 is based on gnome3.18, so it's not supported) 
here is what you should do:

- sudo add-apt-repository ppa:gnome3-team/gnome3-staging
- sudo add-apt-repository ppa:gnome3-team/gnome3
- sudo apt-get update
- sudo apt-get dist-upgrade

**Comment by Gminator22** [comment]
Thanks a lot! I'm new to linux, so I'm not sure how everything works yet.. That helped, the theme works just fine now!
Thanks again! :)
